### ISSUE TITLE
TypeError: Uncaught error: Cannot read property 'find' of null

### ISSUE THREAD

**Issue by dmamaril** [evan-king/joi-validate-json#1]
Hi,

This error gets thrown when I have an invalid path that doesn't match the schema. I've wrapped it in a try block in the meantime, but it'd be neat to get this safeguarded.

```
Debug: internal, implementation, error
    TypeError: Uncaught error: Cannot read property 'find' of null
    at /Users/don.mamaril/Workspace/apps/gsm/goldenstatemaids-hapi/node_modules/joi-validate-patch/lib/joi-validate-patch.js:63:45
    at Array.forEach (native)
    at getValidator (/Users/don.mamaril/Workspace/apps/gsm/goldenstatemaids-hapi/node_modules/joi-validate-patch/lib/joi-validate-patch.js:48:11)
    at validateStep (/Users/don.mamaril/Workspace/apps/gsm/goldenstatemaids-hapi/node_modules/joi-validate-patch/lib/joi-validate-patch.js:85:16)
    at /Users/don.mamaril/Workspace/apps/gsm/goldenstatemaids-hapi/node_modules/joi-validate-patch/lib/joi-validate-patch.js:159:24
    at Array.every (native)
    at Object.exports.validate (/Users/don.mamaril/Workspace/apps/gsm/goldenstatemaids-hapi/node_modules/joi-validate-patch/lib/joi-validate-patch.js:158:11)
    at handler (/Users/don.mamaril/Workspace/apps/gsm/goldenstatemaids-hapi/lib/customer/updateCustomer.js:57:42)
    at Object.exports.execute.internals.prerequisites.internals.handler.callback [as handler] (/Users/don.mamaril/Workspace/apps/gsm/goldenstatemaids-hapi/node_modules/hapi/lib/handler.js:99:36)
    at /Users/don.mamaril/Workspace/apps/gsm/goldenstatemaids-hapi/node_modules/hapi/lib/handler.js:30:23
    at null.internals.Protect.run.finish [as run] (/Users/don.mamaril/Workspace/apps/gsm/goldenstatemaids-hapi/node_modules/hapi/lib/protect.js:59:12)
    at exports.execute.finalize (/Users/don.mamaril/Workspace/apps/gsm/goldenstatemaids-hapi/node_modules/hapi/lib/handler.js:24:22)
    at each (/Users/don.mamaril/Workspace/apps/gsm/goldenstatemaids-hapi/node_modules/hapi/lib/request.js:382:16)
    at iterate (/Users/don.mamaril/Workspace/apps/gsm/goldenstatemaids-hapi/node_modules/hapi/node_modules/items/lib/index.js:36:13)
    at done (/Users/don.mamaril/Workspace/apps/gsm/goldenstatemaids-hapi/node_modules/hapi/node_modules/items/lib/index.js:28:25)
    at request._protect.run (/Users/don.mamaril/Workspace/apps/gsm/goldenstatemaids-hapi/node_modules/hapi/lib/validation.js:68:20)
```

**Comment by evan-king** [comment]
Can you post a code sample to reproduce?  I need to see how your scenario differs from those covered in the unit tests.

**Comment by evan-king** [comment]
Unable to reproduce,  Unit tests cover invalid, out-of-paths schemas and pass, hence additional evidence/details neede (i.e. [mcve](https://stackoverflow.com/help/mcve)).
